#!/bin/bash

# debug
# set -x

#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

PLAY_PATH="${OPENSHIFT_REPO_DIR}"

cd "$OPENSHIFT_DATA_DIR"

exit 0