#!/bin/bash

## stop play application
${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop

if [[ ! $? -eq 0 ]]; then
  echo "Error: could not stop play application"
exit 1

fi

cd "$OPENSHIFT_REPO_DIR"

# clean everything
echo "./activator clean" >> $LOG_FILE
$PLAY_COMMAND clean &> $LOG_FILE

export PLAY_LOG_PATH=${OPENSHIFT_LOG_DIR}
echo "./activator start" >> $LOG_FILE
nohup bash -c "./activator start&> $LOG_FILE" &> /dev/null &

if [[ ! $? -eq 0 ]]; then
  echo "Error: starting play application"
  exit 1
fi

exit 0
